version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: guzzlehttp/guzzle
    versions:
    - "< 7, >= 6.0.a"
  - dependency-name: aws/aws-sdk-php
    versions:
    - 3.172.0
    - 3.172.4
    - 3.173.14
    - 3.173.19
    - 3.173.24
    - 3.173.5
    - 3.173.9
    - 3.174.0
    - 3.175.1
    - 3.176.3
    - 3.176.8
    - 3.178.2
